### ISSUE TITLE
YAML Error

### ISSUE THREAD

**Issue by tfcarlin** [screekworkshop/screek-light-sensor#5]
I'm having trouble installing with the suggested YAML.

Error:

```
INFO ESPHome 2025.2.1
INFO Reading configuration /config/esphome/luxsensor.yaml...
Failed config

esphome: [source /config/esphome/luxsensor.yaml:2]
  
  Platform missing. You must include one of the available platform keys: rp2040, rtl87xx, host, libretiny, bk72xx, esp8266.
  name: luxsensor-mbr
  comment: Screek Light-Sensor LS1
  friendly_name: LuxSensor-MBR
  name_add_mac_suffix: False
  platformio_options: 
    board_build.flash_mode: dio
  project: 
    name: Screek.Light_Sensor
    version: 1A

```
YAML

```
esphome:
  name: luxsensor-mbr
  comment: Screek Light-Sensor LS1
  friendly_name: LuxSensor-MBR
  name_add_mac_suffix: False
  platformio_options:
    board_build.flash_mode: dio
  project: 
    name: Screek.Light_Sensor
    version: 1A

esp32:
  board: lolin_c3_mini
  framework:
    type: arduino
    version: 2.0.9
    platform_version: 6.3.0

external_components:
  - source:
      type: git
      url: https://github.com/screekworkshop/custom_components_support_for_screek_1w
      ref: main
    components: [esp32, uart]

# Enable logging
logger:

wifi:
  ap:
    ssid: "SCREEK-MULTI-SENSOR-1A"
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none

# Enable Home Assistant API
api:
  encryption:
    key: xxx

ota:
  platform: esphome
  
web_server:
  port: 80

captive_portal:

improv_serial:

i2c:
  sda: GPIO7
  scl: GPIO11
  scan: true
  id: bus_a

binary_sensor:
  - platform: status
    name: Online
    id: ink_ha_connected

sensor:
  - platform: template
    id: sys_esp_temperature
    name: ESP Temperature
    lambda: return temperatureRead();
    unit_of_measurement: °C
    device_class: TEMPERATURE
    update_interval: 45s
    entity_category: "diagnostic"
  - platform: uptime
    name: ESP Uptime
    id: sys_uptime
    update_interval: 60s
  - platform: wifi_signal 
    name: RSSI
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"
  - platform: template
    id: esp_memory
    icon: mdi:memory
    name: ESP Free Memory
    lambda: return heap_caps_get_free_size(MALLOC_CAP_INTERNAL) / 1024;
    unit_of_measurement: 'kB'
    state_class: measurement
    entity_category: "diagnostic"
    update_interval: 60s
    disabled_by_default: True
  - platform: bh1750
    name: "Illuminance"
    # address: 0x23
    update_interval: 1s

light:
  - platform: status_led
    name: sys_status
    pin: GPIO12
    internal: True
    restore_mode: ALWAYS_OFF
  - platform: status_led
    name: sys_status
    pin: GPIO13
    internal: True
    restore_mode: ALWAYS_OFF

button:
  - platform: restart
    icon: mdi:power-cycle
    name: "ESP Reboot"
  - platform: factory_reset
    disabled_by_default: True
    name: Factory Reset
    id: factory_reset_all
```
